[project]
name = "redis-utils"
version = "0.0.1"
description = "Package that consists redis-utils"
authors = [
    { name = "k1llzzy", email = "gekachan04@gmail.com" }
]
requires-python = ">=3.10,<4"
dependencies = [
    "asyncio>=3.4.3",
    "loguru>=0.7.2,<0.8.0",
    "redis-client==0.1.7",
    "pytest-asyncio (==0.26.0)",
    "pydantic_settings>=2.7.1",
]

readme = "README.md"

[tool.poetry]
packages = [{ include = "*", from = "src" }]

[[tool.poetry.source]]
name = "pantheon"
url = "https://packages.pypi.pntheon.ai/simple/"
priority = "supplemental"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
