[project]
name = "twitter-ambassador-utils"
version = "0.0.1"
description = "Package that consists utils for Twitter Ambassador"
authors = [
    {name = "k1llzzy",email = "gekachan04@gmail.com"}
]
requires-python = ">=3.10,<4"
dependencies = [
    "aiohttp (>=3.11.13)",
    "requests-oauthlib>=1.3.0",
    "cryptography (>=2.3.1)",
    "example-package (>=0.0.3,<0.0.4)"
]
readme = "README.md"

[tool.poetry]
packages = [{include = "*", from="src"}]


[[tool.poetry.source]]
name = "pantheon"
url = "https://pantheon-688567299207.d.codeartifact.eu-west-1.amazonaws.com/pypi/pantheon/simple/"
priority = "primary"


[tool.poetry.dependencies]
example-package = {source = "pantheon"}
[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
