[project]
name = "send-openai-request"
version = "0.0.1"
description = "Package that send openai request"
authors = [
    {name = "k1llzzy",email = "gekachan04@gmail.com"}
]
requires-python = ">=3.10,<4"
dependencies = [
    "openai (>=1.63.2,<2.0.0)",
]
readme = "README.md"

[tool.poetry]
packages = [{include = "*", from="src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
