[project]
name = "ai-tools"
version = "0.0.1"
description = "Package that consists ai tools"
authors = [
    { name = "k1llzzy", email = "gekachan04@gmail.com" }
]
requires-python = ">=3.10,<4"
dependencies = [
    "loguru>=0.7.2,<0.8.0",
    "openai (>=1.63.2,<2.0.0)",
    "aiohttp (>=3.11.13)",
    "tenacity (>=8.1.0,!=8.4.0,<10)",
    "asyncio (>=3.4.3)",
    "pytest-asyncio (==0.26.0)",
    "send-openai-request (==0.1.2)",
    "pydantic_settings>=2.7.1",
]

readme = "README.md"

[tool.poetry]
packages = [{ include = "*", from = "src" }]

[[tool.poetry.source]]
name = "pantheon"
url = "https://packages.pypi.pntheon.ai/simple/"
priority = "supplemental"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
